/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minesweeper;

import java.awt.Color;
import javax.swing.*;
import javax.swing.ImageIcon;
import java.net.*;
import java.io.*;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.*;
        


/**
 *
 * @author User
 */
public class endMatch extends javax.swing.JFrame {
     private boolean result;
     
     
    /**
     * Creates new form endMatch
     */
    public endMatch(boolean result) throws UnsupportedAudioFileException, IOException, LineUnavailableException {
        StretchIcon img=new StretchIcon(getClass().getResource("/minesweeper/mine26.png"));
        
        this.setIconImage(img.getImage());
        initComponents();
        this.result=result;
        
        this.setVisible(true);
        this.setLocation(0, 200);
        URL url = this.getClass().getResource("/minesweeper/Lose.gif");
        StretchIcon Lose = new StretchIcon(getClass().getResource("/minesweeper/Lose.gif"));
        StretchIcon Win= new StretchIcon(getClass().getResource("/minesweeper/Win.gif"));
        
        
        if(result==true){
            
            this.playSound("src/minesweeper/fireworks.wav");
            resultmessage.setText("Συγχαρητήρια Κερδίσατε !!!");
            jLabel5.setText("Δοκιμάστε άλλη δυσκολία.");
            iconresult.setIcon(Win);
            }
            else{
                this.playSound("src/minesweeper/minexplosion.wav");
                resultmessage.setText("Δυστυχώς Χάσατε :(");
                jLabel5.setText("Ίσως να θέλατε να δείτε τις οδηγίες πρώτα από το μενού");
                iconresult.setIcon(Lose);
                    
                }
        
        
         Handler.JButtonListener(NewGame);
         Handler.JButtonListener(ReturnMenu);
         Handler.JButtonListener(Exit);
         
         this.getContentPane().setBackground(new Color(51,154,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewGame = new javax.swing.JButton();
        ReturnMenu = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        difficulty = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        resultmessage = new javax.swing.JLabel();
        iconresult = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Τέλος Παρτίδας");
        setBackground(new java.awt.Color(51, 154, 255));
        setResizable(false);

        NewGame.setFont(new java.awt.Font("Source Serif Pro Black", 0, 12)); // NOI18N
        NewGame.setForeground(java.awt.Color.orange);
        NewGame.setText("Νέα Παρτίδα");
        NewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGameActionPerformed(evt);
            }
        });

        ReturnMenu.setFont(new java.awt.Font("Source Serif Pro Black", 0, 12)); // NOI18N
        ReturnMenu.setForeground(java.awt.Color.orange);
        ReturnMenu.setText("Επιστροφή στο μενού");
        ReturnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnMenuActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Source Serif Pro Black", 0, 12)); // NOI18N
        Exit.setForeground(java.awt.Color.orange);
        Exit.setText("Έξοδος");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        difficulty.setBackground(new java.awt.Color(51, 154, 255));
        difficulty.setForeground(new java.awt.Color(0, 0, 0));
        difficulty.setMajorTickSpacing(1);
        difficulty.setMaximum(3);
        difficulty.setMinimum(1);
        difficulty.setMinorTickSpacing(1);
        difficulty.setSnapToTicks(true);
        difficulty.setValue(1);
        difficulty.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Επιλογή Δυσκολίας (Ναρκες):");

        jLabel2.setText("10");

        jLabel3.setText("40");

        jLabel4.setText("90");

        resultmessage.setFont(new java.awt.Font("Liberation Serif", 1, 24)); // NOI18N
        resultmessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        iconresult.setBackground(new java.awt.Color(51, 154, 255));
        iconresult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minesweeper/Lose.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NewGame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReturnMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Exit)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(74, 74, 74)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconresult, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resultmessage, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                        .addGap(55, 55, 55)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(resultmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(iconresult, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewGame)
                    .addComponent(ReturnMenu)
                    .addComponent(Exit))
                .addGap(26, 26, 26))
        );

        iconresult.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGameActionPerformed
        Window.disposeframe();
        Grid.cellGrid.clear();
        
        Minesweeper game = new Minesweeper(difficulty.getValue(),1);
        
        setVisible(false);
        
       
     
      
    }//GEN-LAST:event_NewGameActionPerformed

    private void ReturnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnMenuActionPerformed
        dispose();
        Window.disposeframe();
        new MainMenu();
    }//GEN-LAST:event_ReturnMenuActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(endMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(endMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(endMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(endMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
      
    }
    

    public boolean isResult() {
        return result;
    }
    
    
    void playSound(String soundFile) throws UnsupportedAudioFileException, IOException, LineUnavailableException {
    File f = new File("./" + soundFile);
    AudioInputStream audioIn = null;  
         try {
             audioIn = AudioSystem.getAudioInputStream(f.toURI().toURL());
         } catch (MalformedURLException ex) {
             Logger.getLogger(endMatch.class.getName()).log(Level.SEVERE, null, ex);
         }
    Clip clip = null;
         try {
             clip = AudioSystem.getClip();
         } catch (LineUnavailableException ex) {
             Logger.getLogger(endMatch.class.getName()).log(Level.SEVERE, null, ex);
         }
    clip.open(audioIn);
    clip.start();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton NewGame;
    private javax.swing.JButton ReturnMenu;
    private javax.swing.JSlider difficulty;
    private javax.swing.JLabel iconresult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel resultmessage;
    // End of variables declaration//GEN-END:variables
}
