/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minesweeper;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.*; 
import javax.swing.plaf.basic.BasicTabbedPaneUI;
/**
 *
 * @author User
 */

/**
 *
 * @author User
 */
public class MainMenu extends javax.swing.JFrame {
    public static int SKIN;
    public JComboBox<String> getMineskin() {
        return mineskin;
    }
    
    
   
    
    
    public  int getDifficulty() {
        return difficulty.getValue();
    }

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        jPanel1.setBackground(new Color(51,154,255));
        this.setBackground(new Color(51,154,255));
        Tabs.setUI(new BasicTabbedPaneUI(){  
        @Override  
        protected int calculateTabAreaHeight(int tab_placement, int run_count, int max_tab_height) {  

                return 0;  

         
    }  
});  
        
        
         Handler.JButtonListener(newgame);
         Handler.JButtonListener(options);
         Handler.JButtonListener(exit);
         Handler.JButtonListener(Exit);
         Handler.JButtonListener(returnToMenu);
         Handler.JButtonListener(returnToMenu1);
         Handler.JButtonListener(newgameOpt);
         Handler.JButtonListener(Instructions);
         
        StretchIcon img=new StretchIcon(getClass().getResource("/minesweeper/mine26.png"));
        
        this.setIconImage(img.getImage());   
         this.setBackground(new Color(51,154,255));
         
         this.setVisible(true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu5 = new javax.swing.JMenu();
        Tabs = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        background = new javax.swing.JLabel();
        newgame = new javax.swing.JButton();
        options = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        Instructions = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        returnToMenu = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        difficulty = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        newgameOpt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        mineskin = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        returnToMenu1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jMenu3.setText("jMenu3");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ναρκαλιευτής");
        setBackground(new java.awt.Color(51, 154, 255));
        setMaximumSize(new java.awt.Dimension(2147483647, 658));
        setResizable(false);

        Tabs.setBackground(new java.awt.Color(51, 154, 255));
        Tabs.setForeground(new java.awt.Color(51, 154, 255));
        Tabs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(51, 154, 255));
        jPanel3.setToolTipText("");
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setOpaque(false);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minesweeper/mam.jpg"))); // NOI18N
        background.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        newgame.setFont(new java.awt.Font("Source Serif Pro Black", 0, 18)); // NOI18N
        newgame.setForeground(new java.awt.Color(204, 204, 0));
        newgame.setText("Νέα Παρτίδα");
        newgame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newgameActionPerformed(evt);
            }
        });

        options.setFont(new java.awt.Font("Source Serif Pro Black", 0, 18)); // NOI18N
        options.setForeground(new java.awt.Color(204, 204, 0));
        options.setText("Επιλογές");
        options.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MINESWEEPER");

        exit.setFont(new java.awt.Font("Source Serif Pro Black", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(204, 204, 0));
        exit.setText("Έξοδος");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        Instructions.setFont(new java.awt.Font("Source Serif Pro Black", 0, 18)); // NOI18N
        Instructions.setForeground(new java.awt.Color(204, 204, 0));
        Instructions.setText("Οδηγίες");
        Instructions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Instructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstructionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newgame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Instructions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newgame, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(options, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exit)
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)))
        );

        Tabs.addTab("", jPanel3);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        returnToMenu.setFont(new java.awt.Font("Source Serif Pro Black", 0, 18)); // NOI18N
        returnToMenu.setForeground(java.awt.Color.orange);
        returnToMenu.setText("Επιστροφή στο Μενού");
        returnToMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToMenuActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Source Serif Pro Black", 0, 18)); // NOI18N
        Exit.setForeground(java.awt.Color.orange);
        Exit.setText("Έξοδος");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        difficulty.setBackground(new java.awt.Color(51, 154, 255));
        difficulty.setForeground(new java.awt.Color(255, 0, 51));
        difficulty.setMajorTickSpacing(1);
        difficulty.setMaximum(3);
        difficulty.setMinimum(1);
        difficulty.setMinorTickSpacing(1);
        difficulty.setSnapToTicks(true);
        difficulty.setValue(1);
        difficulty.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setText("10 ");

        jLabel2.setText("40");

        jLabel3.setText("90");

        newgameOpt.setFont(new java.awt.Font("Source Serif Pro Black", 0, 18)); // NOI18N
        newgameOpt.setForeground(java.awt.Color.orange);
        newgameOpt.setText("Έναρξη Παρτίδας");
        newgameOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newgameOptActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Επιλογή Δυσκολίας (Νάρκες):");

        mineskin.setBackground(new java.awt.Color(0, 102, 204));
        mineskin.setForeground(new java.awt.Color(0, 0, 0));
        mineskin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Κόκκινη", "Γκρι" }));
        mineskin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mineskinActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Χρώμα Νάρκης:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MINESWEEPER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel2)
                                .addGap(74, 74, 74)
                                .addComponent(jLabel3))
                            .addComponent(difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(mineskin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(172, 172, 172))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(returnToMenu)
                .addGap(57, 57, 57)
                .addComponent(newgameOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mineskin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newgameOpt)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        Tabs.addTab("", jPanel1);

        jPanel2.setOpaque(false);

        returnToMenu1.setFont(new java.awt.Font("Source Serif Pro Black", 0, 18)); // NOI18N
        returnToMenu1.setForeground(new java.awt.Color(255, 153, 0));
        returnToMenu1.setText("Επιστροφή στο Μενού");
        returnToMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnToMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToMenu1ActionPerformed(evt);
            }
        });

        jLabel8.setText("<html>\n<h style=\"color:red;\">Οδηγίες προς νέους ναρκαλιευτές:</h>\n<p>\t&emsp;\tΣκοπός του  παιχνιδού: </p>\n <br></br>\n<p>\tΣκοπός του παιχνιδιού είναι η αποκάλυψη όλων των διαχωρισμών της θάλασσας(κελιών) εκτός αυτών που περιέχουν νάρκη.Κάθε φορά που αποκαλύπτετε ένα κελί και αυτό αν δέν είναι νάρκη τότε σας εμφανίζεται ο αριθμός ναρκών σε γειτονικά κελιά (πάνω,κάτω,δεξιά,αριστερά και διαγώνια) ή σας εμφανίζονται όλα τα κενά έως εκέι που γειτονεύει νάρκη.Αντίθετα αν αποκαλύψετε μιά νάρκη, αυτή εκρήγνυται και το παιχνίδι τελειώνει .Γι αυτό ΠΡΟΣΟΧΗ!!! Αν είστε σίγουροι για το που υπάρχει νάρκη τοποθετήστε σημαιάκι ώστε να μη μπορείται να τη πατήσετε.<p>\n<br></br>\n<p>&emsp;\tΧειρισμός:</p>\n<br></br>\n<p>                  &emsp; &emsp;&emsp;Αριστερό κλικ: Αποκάλυψη κελιού\n<br></br>\n                          &emsp; &emsp;&emsp; Δεξί κλικ: Τοποθέτηση Σημαίας\n<br></br>\n\t&emsp; Ρυθμίσεις:\n<br></br>\n\tΑπό το μενού επιλογές μπορείτε να επιλέξετε επίπεδο δυσκολίας που συνεπάγεται με τον  συνολικό αριθμό ναρκών (10,40 ή 90)\nκαθώς και να εξατομικεύσετε το χρώμα αυτών.Καλό ψάρεμα!! </p>\n</html>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnToMenu1))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnToMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        Tabs.addTab("tab3", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     

    private void optionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsActionPerformed
             Tabs.setSelectedIndex(1); // Goes to SubMenu
    }//GEN-LAST:event_optionsActionPerformed

    private void newgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newgameActionPerformed
          Minesweeper game = new Minesweeper(this.difficulty.getValue(),this.mineskin.getSelectedIndex());
          this.dispose();
          
    }//GEN-LAST:event_newgameActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0); // Terminates ALL threads
    }//GEN-LAST:event_exitActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0); // Terminates ALL threads
    }//GEN-LAST:event_ExitActionPerformed

    private void returnToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToMenuActionPerformed
        Tabs.setSelectedIndex(0); // Returns to MainMenu
    }//GEN-LAST:event_returnToMenuActionPerformed

    private void mineskinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mineskinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mineskinActionPerformed

    private void newgameOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newgameOptActionPerformed
        // TODO add your handling code here:
        Minesweeper game = new Minesweeper(this.difficulty.getValue(),mineskin.getSelectedIndex());
        this.dispose();
    }//GEN-LAST:event_newgameOptActionPerformed

    private void InstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstructionsActionPerformed
        // TODO add your handling code here:
        Tabs.setSelectedIndex(2);
    }//GEN-LAST:event_InstructionsActionPerformed

    private void returnToMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToMenu1ActionPerformed
                // TODO add your handling code here:
        Tabs.setSelectedIndex(0);
    }//GEN-LAST:event_returnToMenu1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Instructions;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JLabel background;
    private javax.swing.JSlider difficulty;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JComboBox<String> mineskin;
    private javax.swing.JButton newgame;
    private javax.swing.JButton newgameOpt;
    private javax.swing.JButton options;
    private javax.swing.JButton returnToMenu;
    private javax.swing.JButton returnToMenu1;
    // End of variables declaration//GEN-END:variables
}
